/*
 * @lc app=leetcode id=389 lang=java
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (52.71%)
 * Total Accepted:    140.8K
 * Total Submissions: 266.1K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
class Solution {
    // public char findTheDifference(String s, String t) {
    //     int[] table = new int[26];
    //     for(char c : t.toCharArray()) {
    //         table[c - 'a']++;
    //     }
    //     for(char c : s.toCharArray()) {
    //         table[c - 'a']--;
    //     }
    //     for(int i = 0; i < table.length; ++i) {
    //         if(table[i] == 1) return (char)('a'+i);
    //     }
    //     return 'a';
    // }
    /**
     * Bit Manipulation
     * @param s
     * @param t
     * @return
     */
    public char findTheDifference(String s, String t) {
        char xor = 0;
        for(char c : s.toCharArray()) xor ^= c;
        for(char c : t.toCharArray()) xor ^= c;
        return xor;
    }
}

